filterbank: # Filterbank config
  n_filters: 128
  kernel_size: 8
  stride: 8
  enc_activation: relu
  fb_name: free
separator: # Network config
  w2v_ckpt: /mnt/scratch07/hushell/UploadAI/ckpts/wav2vec_small.pt
  freeze_w2v: False
  d_model: 128
  nhead: 4
  num_encoder_layers: 6
  num_decoder_layers: 6
  dim_feedforward: 2048
  dropout: 0.1
  activation: relu
  normalize_before: False
  return_intermediate_dec: False
avatar: # Avatar config
  n_spk: 10 # number of speakers
  embed_dim: 128
training: # Training config
  epochs: 200 
  batch_size: 4
  num_workers: 16
  lr_scheduler: plateau
  early_stop: yes
  gradient_clipping: 5
  gpus: -1 # all gpus
optim: # Optim config
  optimizer: adam
  lr: 0.001
  weight_decay: !!float 1e-5
# Data config
data:
  task: enh_single
  root: ../datasets/Avatar10Mix2
  sample_rate: 8000
  n_src: 2
  segment: 3 # length (sec) of input audios
  n_shot: -1 # number of shots per speaker (-1 means not used)
