filterbank: # Filterbank config
  n_filters: 128
  kernel_size: 16
  stride: 8
separator: # Network config
  in_chan: 128
  n_src: 1 # In enh_single, n_src = 1
  ff_hid: 256
  chunk_size: 100
  hop_size: 50
  n_repeats: 5
  norm_type: "gLN"
  ff_activation: "relu"
  mask_act: 'sigmoid'
  bidirectional: true
  dropout: 0
avatar: # Avatar config
  n_spk: 10
  emb_dim: 512
training: # Training config
  epochs: 200
  batch_size: 4
  num_workers: 16
  lr_scheduler: yes
  early_stop: yes
  gradient_clipping: 5
  gpus: -1 # all gpus
optim: # Optim config
  optimizer: adam
  lr: 0.001
  weight_decay: !!float 1e-5
scheduler:
  steps_per_epoch: 10000
  d_model: 64
# Data config
data:
  task: enh_single
  train_dir: data_10+10/wav8k/min/train-100-openset100+10-test
  valid_dir: data_10+10/wav8k/min/train-100-openset100+10-test
  sample_rate: 8000
  n_src: 2
  segment: 3
  n_shot: 3
